[apiontap:qtrees]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0

[apiontap:aggregates]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0

[apiontap:volume]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0

[apiontap:svms]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0

[apiontap:cluster_nodes]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0

[apiontap:cluster_identity]
DATETIME_CONFIG = CURRENT
KV_MODE = json
SHOULD_LINEMERGE = false
TRUNCATE = 0
