[logging]
loglevel = INFO

[data_collection]
account =
index = default
interval = 300
request_timeout = 30
collect_qtrees = 1
collect_aggregates = 1
collect_volume = 1
collect_svms = 1
collect_cluster_nodes = 1
collect_cluster_identity = 1
