[expose:Splunk_TA_NetApp_ontap_account]
pattern = Splunk_TA_NetApp_ontap_account
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_account_specified]
pattern = Splunk_TA_NetApp_ontap_account/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_settings]
pattern = Splunk_TA_NetApp_ontap_settings
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_settings_specified]
pattern = Splunk_TA_NetApp_ontap_settings/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_qtrees]
pattern = Splunk_TA_NetApp_ontap_qtrees
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_qtrees_specified]
pattern = Splunk_TA_NetApp_ontap_qtrees/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_aggregates]
pattern = Splunk_TA_NetApp_ontap_aggregates
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_aggregates_specified]
pattern = Splunk_TA_NetApp_ontap_aggregates/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_volume]
pattern = Splunk_TA_NetApp_ontap_volume
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_volume_specified]
pattern = Splunk_TA_NetApp_ontap_volume/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_svms]
pattern = Splunk_TA_NetApp_ontap_svms
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_svms_specified]
pattern = Splunk_TA_NetApp_ontap_svms/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_cluster_nodes]
pattern = Splunk_TA_NetApp_ontap_cluster_nodes
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_cluster_nodes_specified]
pattern = Splunk_TA_NetApp_ontap_cluster_nodes/*
methods = POST, GET, DELETE

[expose:Splunk_TA_NetApp_ontap_cluster_identity]
pattern = Splunk_TA_NetApp_ontap_cluster_identity
methods = POST, GET

[expose:Splunk_TA_NetApp_ontap_cluster_identity_specified]
pattern = Splunk_TA_NetApp_ontap_cluster_identity/*
methods = POST, GET, DELETE

[expose:data/indexes]
pattern = data/indexes
methods = GET

[expose:Splunk_TA_NetApp_ontap_data_collection_page]
pattern = Splunk_TA_NetApp_ontap/data_collection
methods = GET
